pipeline:
  identifier: Build_Krishna_hub_spec_Harness_Test_1726687446460
  name: Build Harness_Test
  orgIdentifier: default
  projectIdentifier: Node_Test
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1724188462314
        repoName: Krishna-hub-spec/Harness_Test
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - parallel:
                  - step:
                      identifier: installdependencies
                      name: install dependencies
                      spec:
                        command: npm install
                      timeout: ""
                      type: Run
                  - step:
                      type: Run
                      name: Run_3
                      identifier: Run_3
                      spec:
                        shell: Sh
                        command: echo "Hello World!"
              - step:
                  identifier: test
                  name: test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    caching: true
                    connectorRef: <+input>
                    repo: hello/world
                    tags:
                      - latest
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
